### ISSUE TITLE
size parameter

### ISSUE THREAD

**Issue by PaulZH** [jprante/elasticsearch-index-termlist#11]
When I use as size parameter a value that is equal or bigger than total, I do not get back all results.

E.g. _termlist?field=autocomplete_object&term=kan&size=6

    total: 4,
    terms: [
    {
    name: “kandelaars”
    },
    {
    name: “kandelabers”
    },
    {
    name: “kantoorstempels”
    }
]

E.g. _termlist?field=autocomplete_object&term=kan&size=4

    total: 4,
    terms: [
    {
    name: “kandelaars”
    },
   {
   name: “kandelabers”
   },
   {
   name: “kantoorstempels”
   }
   ]

What am I missing?

**Comment by jprante** [comment]
Thanks, good catch! I released 1.4.0.1 with a fix.

**Comment by DirkDE** [comment]
It seems the issue is not completely fixed yet.

Our plugin versions (running on a cluster):
URL=*/es/_cat/plugins
  anna index-termlist-1.4.0.1-6f289d0 1.4.0.1 j  
  lena index-termlist-1.4.0.1-6f289d0 1.4.0.1 j  

Full termlist (no size prameter):
URL=*/es/test/artefact/_termlist?field=autocomplete_person&term=rub&totalfreqs&sortbytotalfreqs&pretty=true
{
  "_shards" : {
    "total" : 5,
    "successful" : 5,
    "failed" : 0
  },
  "total" : 2,
  "terms" : [ {
    "name" : "rubbens",
    "totalfreq" : 49
  }, {
    "name" : "rubens",
    "totalfreq" : 14
  } ]
}

Same termlist with (any) size parameter:
URL=*/es/test/artefact/_termlist?field=autocomplete_person&term=rub&totalfreqs&sortbytotalfreqs&pretty=true&size=100
{
  "_shards" : {
    "total" : 5,
    "successful" : 5,
    "failed" : 0
  },
  "total" : 2,
  "terms" : [ {
    "name" : "rubbens",
    "totalfreq" : 49
  } ]
}

Could you please check?
Thanks!

**Comment by DirkDE** [comment]
Hi,
Any news on this issue? If you need additional info just let me know.
Txs!
